### ISSUE TITLE
Will it work on linux?

### ISSUE THREAD

**Issue by ghost** [afifaniks/FileRetriever#1]
I asked this because  linux is differ from windows os.

**Comment by afifaniks** [comment]
It will not work on linux properly for the time being.

**Comment by ghost** [comment]
I want to make a file receiver for linux.

How can I do it with this project?

why this project will  not work  in linux?

Can you give any information?

**Comment by ghost** [comment]
I think  [this][1] code will work on linux.

But , why you say it will not work?


  [1]: https://github.com/afifaniks/FileRetriever/blob/master/PC_Server/src/server/Controller.java

**Comment by afifaniks** [comment]
> I want to make a file receiver for linux.
> 
> How can I do it with this project?
> 
> why this project will not work in linux?
> 
> Can you give any information?

This project will definitely run on linux. However, it will not work properly on the Android client as windows file path varies from linux and I haven't considered this in this release. To make it work for linux you will have to take care of that. For example windows path separator can be indicated by ("\\") where in linux it is done by ("/"). Take care of this in the Android client and you are good to go.

**Comment by ghost** [comment]
https://github.com/afifaniks/FileRetriever/blob/master/Android_Client/app/src/main/java/me/afifaniks/fileretriever/ListAdapter.java#L50


When I set the path separator like this "/" .will it work?

Can you give more information?

I want to make a file receiver for linux . But , I have some confusions in this project. 

where can I set the path separator for linux?

Can you give more information?
